CREATE TABLE tbl_users (
  User_ID INT(11) NOT NULL AUTO_INCREMENT,
  Username VARCHAR(30) NOT NULL,
  Pwd VARCHAR(255) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Created_at DATETIME NOT NULL DEFAULT CURRENT_TIME
);